[workspace]
resolver = "2"
members = [
    "crates/maskman",
    "crates/maskman-config",
    "crates/maskman-protocol",
    "crates/maskman-server",
    "crates/maskman-platform",
    "crates/maskman-update",
]
default-members = ["crates/maskman"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["BackRunner <dev@backrunner.top>"]
rust-version = "1.88"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
