[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
maskman-protocol = { path = "../crates/maskman-protocol", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
toml = "0.8"

[lints]
workspace = true
